LANDS = {
    "Azorius Guildgate",
    "Blast Zone",
    "Blood Crypt",
    "Bloodfell Caves",
    "Blossoming Sands",
    "Boros Guildgate",
    "Breeding Pool",
    "Castle Ardenvale",
    "Castle Embereth",
    "Castle Garenbrig",
    "Castle Locthwain",
    "Castle Vantress",
    "Command Tower",
    "Cryptic Caves",
    "Dimir Guildgate",
    "Dismal Backwater",
    "Dwarven Mine",
    "Emergence Zone",
    "Evolving Wilds",
    "Fabled Passage",
    "Field of Ruin",
    "Forest",
    "Gateway Plaza",
    "Gingerbread Cabin",
    "Godless Shrine",
    "Golgari Guildgate",
    "Gruul Guildgate",
    "Guildmages' Forum",
    "Hallowed Fountain",
    "Idyllic Grange",
    "Interplanar Beacon",
    "Island",
    "Izzet Guildgate",
    "Jungle Hollow",
    "Karn's Bastion",
    "Labyrinth of Skophos",
    "Lotus Field",
    "Mobilized District",
    "Mountain",
    "Mystic Sanctuary",
    "Orzhov Guildgate",
    "Overgrown Tomb",
    "Plains",
    "Plaza of Harmony",
    "Rakdos Guildgate",
    "Rugged Highlands",
    "Sacred Foundry",
    "Scoured Barrens",
    "Selesnya Guildgate",
    "Simic Guildgate",
    "Steam Vents",
    "Stomping Ground",
    "Swamp",
    "Swiftwater Cliffs",
    "Temple Garden",
    "Temple of Abandon",
    "Temple of Deceit",
    "Temple of Enlightenment",
    "Temple of Epiphany",
    "Temple of Malady",
    "Temple of Malice",
    "Temple of Mystery",
    "Temple of Plenty",
    "Temple of Silence",
    "Temple of Triumph",
    "Thornwood Falls",
    "Tournament Grounds",
    "Tranquil Cove",
    "Unknown Shores",
    "Watery Grave",
    "Wind-Scarred Crag",
    "Witch's Cottage",
}
BASICS = {"Plains", "Island", "Swamp", "Mountain", "Forest"}
